/*
 * generated by Xtext 2.12.0
 */
package de.jugh


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ArkanoidDslStandaloneSetup extends ArkanoidDslStandaloneSetupGenerated {

	def static void doSetup() {
		new ArkanoidDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
