/*
 * generated by Xtext 2.12.0
 */
package de.jugh.ide

import com.google.inject.Guice
import de.jugh.ArkanoidDslRuntimeModule
import de.jugh.ArkanoidDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class ArkanoidDslIdeSetup extends ArkanoidDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new ArkanoidDslRuntimeModule, new ArkanoidDslIdeModule))
	}
	
}
