/*
 * generated by Xtext 2.12.0
 */
package de.jugh.validation

import de.jugh.arkanoidDsl.GameContentProvider
import java.util.ArrayList
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class ArkanoidDslValidator extends AbstractArkanoidDslValidator {

	@Check
	def checkLevelIDUnique(GameContentProvider content) {
		if (content.level.empty) {
			return
		}

		val levelIds = new ArrayList();

		content.level.forEach [
			if (levelIds.contains(it.name)) {
				warning("Level id has to bee unique", it, null);
			} else {
				levelIds.add(it.name)
			}
		]
	}
}
